# Generated by Django 5.0.3 on 2024-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
