# Generated by Django 5.0.3 on 2024-03-13 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=120)),
                ('rentPayDate', models.DateField()),
                ('rentEndDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.customuser')),
            ],
        ),
    ]
