# Generated by Django 5.0.3 on 2024-03-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_alter_client_user_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='creator_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
