# Generated by Django 5.0.3 on 2024-03-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_client_creator_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_login_as_guest', 'Can log in as guest'), ('cant_login_as_host', 'Can not log in as host')],
            },
        ),
    ]
