# Generated by Django 5.0.3 on 2024-03-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_remove_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
