# Generated by Django 5.0.3 on 2024-03-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='raw_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
