# Generated by Django 5.0.3 on 2024-03-20 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0013_client_raw_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='raw_password',
        ),
    ]
