# Generated by Django 5.0.3 on 2024-03-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0017_remove_message_recipient_message_recipient_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='creator_id',
            field=models.IntegerField(default=None),
        ),
    ]
